package com.uptos.votacion.model;  
// Generated 14-feb-2017 20:31:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int id;
     private String cedula;
     private String nombres;
     private String apellidos;
     private Boolean estado;
     private String carrera;
     private Set procesos = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(int id, String cedula, String nombres, String apellidos) {
        this.id = id;
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Estudiante(int id, String cedula, String nombres, String apellidos, Boolean estado, String carrera, Set procesos) {
       this.id = id;
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.estado = estado;
       this.carrera = carrera;
       this.procesos = procesos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Set getProcesos() {
        return this.procesos;
    }
    
    public void setProcesos(Set procesos) {
        this.procesos = procesos;
    }




}


