package com.uptos.votacion.model;  
// Generated 14-feb-2017 20:31:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plancha generated by hbm2java
 */
public class Plancha  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Integer votos;
     private Set procesos = new HashSet(0);

    public Plancha() {
    }

	
    public Plancha(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Plancha(int id, String nombre, Integer votos, Set procesos) {
       this.id = id;
       this.nombre = nombre;
       this.votos = votos;
       this.procesos = procesos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getVotos() {
        return this.votos;
    }
    
    public void setVotos(Integer votos) {
        this.votos = votos;
    }
    public Set getProcesos() {
        return this.procesos;
    }
    
    public void setProcesos(Set procesos) {
        this.procesos = procesos;
    }




}


